### ISSUE TITLE
応答のないJSONを処理するとエラー出力が発生する

### ISSUE THREAD

**Issue by kasshisatari** [kasshisatari/PetitKara#32]
**現象**
stderr.logに例外が出力される。

**再現手順**
Windowsに移植する。
http://localhost:8080 を表示する。

**期待される挙動**
stderr.logに例外が出力されない。

**不具合再現確率**
100%

**バージョン**
1.3.21

**ログ(stderr.log)**
serving on 0.0.0.0:8080 view at http://127.0.0.1:8080
Exception happened during processing of request from ('127.0.0.1', 52788)
Traceback (most recent call last):
  File "C:\Desktop\petitkara\PetitKara\paste\httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "C:\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Desktop\petitkara\PetitKara\paste\httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "C:\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Desktop\petitkara\PetitKara\paste\httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "C:\Desktop\petitkara\PetitKara\paste\httpserver.py", line 309, in wsgi_execute
    self.wsgi_write_chunk('')
  File "C:\Desktop\petitkara\PetitKara\paste\httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "C:\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'

**Comment by kasshisatari** [comment]
**原因**
byte列を返すところ、文字列型を返しているため。

**処置**
リテラルをbyte列指定にする。
