### ISSUE TITLE
曲情報が更新できない

### ISSUE THREAD

**Issue by kasshisatari** [kasshisatari/PetitKara#50]
**現象**
曲情報が更新できず、500エラーが発生する。

**再現手順**
Windowsに移植する。
トップページから「曲情報更新」ボタンを押下する。

**期待される挙動**
曲情報が更新され、トップページに遷移する。

**不具合再現確率**
100%

**バージョン**
1.3.29

**ログ(stderr.log)**
Traceback (most recent call last):
  File "C:\PetitKara\trunk\bottle.py", line 997, in _handle
    out = route.call(**args)
  File "C:\PetitKara\trunk\bottle.py", line 2000, in wrapper
    rv = callback(*a, **ka)
  File "Controller.py", line 647, in refresh
    File.init()
  File "C:\PetitKara\trunk\File.py", line 401, in init
    Delete()
  File "C:\PetitKara\trunk\File.py", line 390, in Delete
    os.remove(fileName)
PermissionError: [WinError 32] プロセスはファイルにアクセスできません。別のプロセスが使用中です。: 'file.db'

**Comment by kasshisatari** [comment]
**原因**
DB接続をクローズする関数を呼出さず、関数のアドレスのみを参照していたため。

**処置**
DB接続をクローズする関数を呼出すよう修正する。
