### ISSUE TITLE
割り込み予約できない

### ISSUE THREAD

**Issue by kasshisatari** [kasshisatari/PetitKara#82]
**現象**
割り込み予約できない。
500エラーが発生する。

**再現手順**
割り込み予約する。

**期待される挙動**
割り込み予約が動作する。

**不具合再現確率**
100%

**バージョン**
1.4.12

**ログ(stderr.log)**
Traceback (most recent call last):
  File "C:\PetitKara\trunk\bottle.py", line 997, in _handle
    out = route.call(**args)
  File "C:\PetitKara\trunk\bottle.py", line 2000, in wrapper
    rv = callback(*a, **ka)
  File "Controller.py", line 537, in insert
    False)
  File "C:\PetitKara\trunk\Book.py", line 193, in AddTop
    str(int(dummy)) + ")")
TypeError: can only concatenate str (not "float") to str

**Comment by kasshisatari** [comment]
**原因**
#73対応にてdurationがstr型からfloat型になり、文字列加算に失敗したため。

**処置**
durationをstr型に型変換する。
