### ISSUE TITLE
PetitKaraが起動しない

### ISSUE THREAD

**Issue by kasshisatari** [kasshisatari/PetitKara#83]
**現象**
PetitKaraが起動しない。
Wi-Fiは動作している。
Webサービスが停止している。

**再現手順**
USBキーボードを刺さない状態で起動する。

**期待される挙動**
PetitKaraが起動する。

**不具合再現確率**
100%

**バージョン**
1.4.14

**ログ(stderr.log)**
Traceback (most recent call last):
  File "Controller.py", line 807, in <module>
    keyboard.hook(callback)
  File "/home/pi/Desktop/PetitKara/keyboard/__init__.py", line 459, in hook
    append(callback)
  File "/home/pi/Desktop/PetitKara/keyboard/_generic.py", line 67, in add_handler
    self.start_if_necessary()
  File "/home/pi/Desktop/PetitKara/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/pi/Desktop/PetitKara/keyboard/__init__.py", line 194, in init
    _os_keyboard.init()
  File "/home/pi/Desktop/PetitKara/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/pi/Desktop/PetitKara/keyboard/_nixkeyboard.py", line 110, in build_device
    device = aggregate_devices('kbd')
  File "/home/pi/Desktop/PetitKara/keyboard/_nixcommon.py", line 157, in aggregate_devices
    devices_from_proc = list(list_devices_from_proc(type_name))
  File "/home/pi/Desktop/PetitKara/keyboard/_nixcommon.py", line 131, in list_devices_from_proc
    path = '/dev/input/event' + re.search(r'event(\d+)', handlers).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by kasshisatari** [comment]
**原因**
#72 対応にてキーボードデバイスにアクセスしようとして例外が発生しプログラムが終了したたため。

**処置**
キーボード未接続の例外を無視する。
