### ISSUE TITLE
Raspbian Busterにインストールできない

### ISSUE THREAD

**Issue by kasshisatari** [kasshisatari/PetitKara#95]
**現象**
Raspbian Busterにインストールできない。
インストール後、PetitKaraのコンソール画面が表示されない。

**再現手順**
Raspbian Busterにインストールする。

**期待される挙動**
インストール後、PetitKaraのコンソール画面が表示される。

**不具合再現確率**
100%

**バージョン**
1.4.20

**ログ(stderr.log)**
Traceback (most recent call last):
  File "Controller.py", line 817, in <module>
    img = qrcode.make("WIFI:T:nopass;S:" + network.GetSSID() + ";P:;;")
  File "/home/pi/Desktop/PetitKara/Raspi/Network.py", line 108, in GetSSID
    return ssid
UnboundLocalError: local variable 'ssid' referenced before assignment

**Comment by kasshisatari** [comment]
**原因**
Raspbian Busterにてhostapd.conf.gzが削除されたため。

**処置**
hostapd.confを直接コピーする。
