### ISSUE TITLE
ファイル詳細画面でError: 500 Internal Server Errorが発生する

### ISSUE THREAD

**Issue by kasshisatari** [kasshisatari/PetitKara#96]
**現象**
Error: 500 Internal Server Errorと表示される。

**再現手順**
Windowsでクリーンインストール(install.batを実行)する。
ファイル詳細画面を開く。

**期待される挙動**
ファイル詳細画面が開く。

**不具合再現確率**
100%

**バージョン**
1.4.21

**ログ(stderr.log)**
Traceback (most recent call last):
  File "C:\bottle.py", line 997, in _handle
    out = route.call(**args)
  File "C:\bottle.py", line 2000, in wrapper
    rv = callback(*a, **ka)
  File "Controller.py", line 756, in detail
    page=request.query.page)
  File "C:\bottle.py", line 4223, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\bottle.py", line 4008, in render
    self.execute(stdout, env)
  File "C:\bottle.py", line 3993, in execute
    exec(self.co, env)
  File "C:\views\detail.tpl", line 30, in <module>
    % list = File.Detail(id,name)
  File "C:\File.py", line 355, in Detail
    hour = str(int(videoInfo.GetDuration(filePath) / 3600)).zfill(2)
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by kasshisatari** [comment]
**原因**
ffmpegのURLが途切れ、インストールに失敗したため。

**処置**
特定バージョンのffmpegではなく、最新版のffmpegを取得するように修正する。
